services:
  apache-php:
    image: apache-mysqli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html:z
    ports:
      - "80:80"
    networks:
      -  app-network

  mysql:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
